/**
@copyright Evgeny Sidorov 2026

This software is dual-licensed. Choose the appropriate license for your project.

1. The GNU GENERAL PUBLIC LICENSE, Version 3.0
     (see accompanying file [LICENSE-GPLv3.md](LICENSE-GPLv3.md) or copy at https://www.gnu.org/licenses/gpl-3.0.txt)

2. The GNU LESSER GENERAL PUBLIC LICENSE, Version 3.0
     (see accompanying file [LICENSE-LGPLv3.md](LICENSE-LGPLv3.md) or copy at https://www.gnu.org/licenses/lgpl-3.0.txt).

You may select, at your option, one of the above-listed licenses.

*/

/****************************************************************************/

/** @file demo/demomanager/demoregistry.cpp
*
*  Defines the compiled-in registry of demo applications.
*
*/

/****************************************************************************/

#include "demoregistry.hpp"

//--------------------------------------------------------------------------

const std::vector<DemoInfo>& demoRegistry()
{
    // demoregistry.inc is generated by demo/CMakeLists.txt from the registry
    // collected by uise_demo() calls in every demo/*/CMakeLists.txt.
    static const std::vector<DemoInfo> Registry = {
        #include "demoregistry.inc"
    };
    return Registry;
}

//--------------------------------------------------------------------------
