ADD_EXECUTABLE(${PROJECT_NAME} ${HEADERS} ${SOURCES})

ADD_TEST(NAME ${PROJECT_NAME} COMMAND ${PROJECT_NAME})
SET_TESTS_PROPERTIES(${PROJECT_NAME} PROPERTIES LABELS ALL)

SET (TEST_SUITES "")

FOREACH(SOURCE_FILE_NAME ${SOURCES})

    FILE(READ "${SOURCE_FILE_NAME}" SOURCE_FILE_CONTENTS)

    STRING(REGEX MATCH "BOOST_AUTO_TEST_SUITE\\( *([A-Za-z_0-9]+) *\\)"
           FOUND_TEST_SUITE ${SOURCE_FILE_CONTENTS})

    IF (FOUND_TEST_SUITE)

        STRING(REGEX REPLACE ".*\\( *([A-Za-z_0-9]+) *\\).*" "\\1" SUITE_NAME ${FOUND_TEST_SUITE})

        LIST (FIND TEST_SUITES ${SUITE_NAME} FOUND_IDX)
        IF (${FOUND_IDX} EQUAL -1)
            LIST (APPEND TEST_SUITES ${SUITE_NAME})
            ADD_TEST(NAME ${SUITE_NAME}
                     COMMAND ${PROJECT_NAME}
                     --run_test=${SUITE_NAME})
            SET_TESTS_PROPERTIES(${SUITE_NAME} PROPERTIES LABELS SUITE)
        ENDIF()

        STRING(REGEX MATCHALL "BOOST_AUTO_TEST_CASE\\( *([A-Za-z_0-9]+) *\\)"
               FOUND_TESTS ${SOURCE_FILE_CONTENTS})

        FOREACH(HIT ${FOUND_TESTS})
            STRING(REGEX REPLACE ".*\\( *([A-Za-z_0-9]+) *\\).*" "\\1" TEST_NAME ${HIT})
            ADD_TEST(NAME ${SUITE_NAME}/${TEST_NAME}
                     COMMAND ${PROJECT_NAME}
                     --run_test=${SUITE_NAME}/${TEST_NAME})
        ENDFOREACH()
    ENDIF()

ENDFOREACH()

OPTION(BOOST_STATIC "Use static Boost libraries" OFF)
IF (BOOST_STATIC)
    SET (Boost_USE_STATIC_LIBS ON CACHE BOOL "Boost static libs")
ELSE (BOOST_STATIC)
    SET (Boost_USE_STATIC_LIBS OFF CACHE BOOL "Boost static libs")
    SET(Boost_USE_STATIC_RUNTIME OFF)
    IF(WIN32)
        TARGET_COMPILE_DEFINITIONS(${PROJECT_NAME} PRIVATE -DBOOST_ALL_NO_LIB)
    ENDIF(WIN32)
    TARGET_COMPILE_DEFINITIONS(${PROJECT_NAME} PRIVATE -DBOOST_ALL_DYN_LINK)
ENDIF (BOOST_STATIC)

FIND_PACKAGE(Boost 1.65 COMPONENTS unit_test_framework REQUIRED)
FIND_PACKAGE(Qt6 COMPONENTS Test REQUIRED)

SET (HEADERS
    ${CMAKE_CURRENT_LIST_DIR}/uise/test/uise-test.hpp
    ${CMAKE_CURRENT_LIST_DIR}/uise/test/uise-testwrapper.hpp
    ${CMAKE_CURRENT_LIST_DIR}/uise/test/uise-testthread.hpp
)

SET (SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/main.cpp
    ${CMAKE_CURRENT_LIST_DIR}/uise-testthread.cpp
)

TARGET_SOURCES(${PROJECT_NAME} PRIVATE ${HEADERS} ${SOURCES})
TARGET_INCLUDE_DIRECTORIES(${PROJECT_NAME} PRIVATE ${CMAKE_CURRENT_LIST_DIR})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} PRIVATE ${CMAKE_PROJECT_NAME} ${Boost_LIBRARIES} Qt6::Test)
TARGET_COMPILE_DEFINITIONS(${PROJECT_NAME} PRIVATE "-DUISE_TEST_MODULE=${PROJECT_NAME}")
